name: Docker Image Wordpress TxGame CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t nono92vn/wordpress:latest
    - name: Publish the Docker image
      run: | 
           docker login -u nono92vn -p ${{ secrets.DOCKER_HUB_TOKEN }}
           docker push nono92vn/wordpress:latest      
