name: Docker Image Wordpress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Wordpress TxGame
      run: docker build wordpress --file Dockerfile --tag wordpress:latest
